json.logger:
  disabledFields: ""
  
cnbSystemAPI:
  host: "cnb-contracts-sapi-2a5eys.internal-a3fso7.gbr-e1.cloudhub.io"
  port: "443"
  basePath: "/api"
  responseTimeout: "30000"
  resources:
    serviceContracts: "/contracts"
    serviceContractLines: "/contract-lines"
  reconnection:
    attempts: "2"
    frequency: "2000"
  untilsuccessful:
    serviceContracts:
      retries: "2"
      frequency: "2000"
    serviceContractLines:
      retries: "2"
      frequency: "2000" 
    
serviceContractsPAPI:
  host: "salesforce-service-contract-papi-2a5eys.internal-a3fso7.gbr-e1.cloudhub.io"
  port: "443"
  basePath: "/api"
  resources:
    serviceContracts: "/service-contracts"
    serviceContractLines: "/service-contract-lines"
  responseTimeout: "30000"
  reconnection:
    attempts: "2"
    frequency: "2000"
  untilsuccessful:
    serviceContracts:
      retries: "2"
      frequency: "2000"
    serviceContractLines:
      retries: "2"
      frequency: "2000" 
  
cnbContractsBatch:
  fromDateDiff: "7" # In Minutes 7
  toDateDiff: "0" # In Minutes 0
  serviceContracts:
    parallelThreads: "4"
    parallelVMConsumers: "4"
    batchSize: "100"
    frequency: "5" # In Minutes
    startDelay: "10" # In Minutes
  serviceContractsLines:
    parallelThreads: "4"
    parallelVMConsumers: "4"
    batchSize: "100"
  vmQueues:
    serviceContracts: "vmContractQueue"
    serviceContractLines: "vmContractLineStart"
    
tls.keystore:
  type:         "jks"
  path:         "keystore/keystore.jks"
  alias:        "mule"
  password:     "password"
  keyPassword:  "password"
  
stockCodesDB:
  host: "thsSQL1.uk.access-accounts.com"
  port: "1433"
  databaseName: "Accounts"
  useSSL: "false"
  requireSSL: "false"
  verifyServerCertificate: "false"
  encrypt: "false" 
  untilSucessful:
    maxRetry: "3"
    retryTime: "1000"
  reconnection:
    frequency: "2000"
    attempts: "2"
  connection:
    pooling:
      maxPoolSize: "15"
      minPoolSize: "10"
  
sfdcServiceContractAPI:
  host: "salesforce-service-contract-sapi-2a5eys.internal-a3fso7.gbr-e1.cloudhub.io"
  port: "443"
  basePath: "/api"
  resources:
    stockCodes: "/stock-codes"
  responseTimeout: "30000"
  reconnection:
    frequency: "2000"
    attempts: "2"
  untilSucessful:
    maxRetry: "3"
    retryTime: "3000"
  
  

    
sfdcerrorHospitalAPI:
  host: "error-hospital-sapi-2a5eys.internal-a3fso7.gbr-e1.cloudhub.io"
  port: "443"
  basePath: "/api"
  resources:
    errorHospital: "errors"
  responseTimeout: "30000"
  reconnection:
    frequency: "2000"
    attempts: "2"
  untilSucessful:
    maxRetry: "3"
    retryTime: "3000"
  
stockCodesBatch:
  batchSize: "150"
  concurrency: "4"
  scheduler:
    frequency: "60" # Minutes
    startDelay: "10" # Minutes